### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by LucasCalazans**
Fixing Responsive sidebar example' syntax error.

### CODE REVIEW

**Comment by grsoares21** [comment]
There are other details in this example that can be fixed:
*The constructor initializes the state properties 'open' and 'docked' but in the rest of the document the properties used are 'sidebarOpen' and 'sidebarDocked'
*The render function has a sidebarProps variable that is never used

Is @balloob still managing this repo?

**Comment by balloob** [comment]
I am not managing this repo anymore. I added that to the README in ba00589b0c6cc6bc47ce142eca82798c1a807c6a. @Fallenstedt has taken over maintenance but not clear to me if that is still happening.

**Comment by Fallenstedt** [comment]
To confirm, I have abandoned this entirely.

**Comment by balloob** [comment]
I've updated the README again with a notice of not being maintained 8b95d3d5b22f58d7893ad85e2dee5b6cc82ca02b

**Comment by markusenglund** [comment]
@balloob @Fallenstedt I'm currently using this library and I quite like it. It would be a shame for it to fall into obscurity. Do you guys think it has been outclassed by other libraries or is it just lack of time? Could I take over maintainership of it?

**Comment by markusenglund** [comment]
Ok, I've taken over maintaining the library. I'll merge this PR and fix the other problems with the README soon.

**Comment by grsoares21** [comment]
Great news! I'll be glad to help if ever needed.

**Pull request merged**
