### PR TITLE
Add `rootClassName` props

### PR DESCRIPTION
**Pull request by sugarshin**
plz review

### CODE REVIEW

**Comment by davedc** [comment]
@balloob Any chance to get this merged soon? Just ran into a roadblock that needed other optional classNames as well.

**Comment by balloob** [comment]
Sorry, missed this PR.

@sugarshin can you update the README with the new props and update the changelog?

**Comment by sugarshin** [comment]
@balloob plz check it out

**Comment by davedc** [comment]
@sugarshin @balloob Thanks guys.

**Comment by balloob** [comment]
Looks good! :dolphin:

**Comment by balloob** [comment]
Published 2.1.3: https://www.npmjs.com/package/react-sidebar

**Comment by davedc** [comment]
@sugarshin @balloob just did a quick test. sidebar.js in dist-modules is not bumped to latest yet so changes don't work.

**Comment by balloob** [comment]
oh yes, didn't do a build. Will do tonight and release 2.1.4

On Tue, Jun 21, 2016 at 9:41 AM, davedc <notifications@github.com> wrote:

> @sugarshin <https://github.com/sugarshin> @balloob
> <https://github.com/balloob> just did a quick test. sidebar.js in
> dist-modules is not bumped to latest yet so changes don't work.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/balloob/react-sidebar/pull/50#issuecomment-227498590>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABYJ2iPG5Ai1UkWTdzGK_NfvjoAYzo88ks5qOBQqgaJpZM4IpGaO>
> .
>



-- 
PaulusSchoutsen.nl
It's nice to be important but it's more important to be nice.

**Comment by balloob** [comment]
2.1.4 is up

**Pull request merged**
