### PR TITLE
React 15.2 Unknown prop on div tag fix

### LINKED ISSUE #54: warning.js:44 Warning: Unkown prop `onTouchTap` on <div> tag. Remove this prop from the element
image

### PR DESCRIPTION
**Pull request by factorize**
Ref: arbitrary attributes are supported on custom elements by providing an `is` attribute [https://facebook.github.io/react/docs/jsx-gotchas.html](https://facebook.github.io/react/docs/jsx-gotchas.html)

Fixes #54

### CODE REVIEW

**Comment by balloob** [comment]
The solution is not adding `is`, instead `onTouchTap` should be replaced with `onClick` http://www.html5rocks.com/en/mobile/touchandmouse/#toc-1

**Comment by factorize** [comment]
Thanks, PR amended

**Comment by balloob** [comment]
Your PR has conflicts now . Can you rebase on the latest `master` branch?

**Comment by factorize** [comment]
Here you go

**Comment by balloob** [comment]
Published as 2.2!

**Comment by cristian-sima** [comment]
Thank you

**Pull request merged**
